api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Game Journey API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.oas.openapi+json', 'application/vnd.api+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
            max_age: 3600
            shared_max_age: 3600
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_enabled: true
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
        pagination_client_enabled: true
        order: { id: 'ASC' }
    keep_legacy_inflector: false
    use_symfony_listeners: true
    eager_loading:
        enabled: true
        fetch_partial: true
        force_eager: false
    exception_to_status:
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 404
        Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: 403
        Symfony\Component\HttpKernel\Exception\BadRequestHttpException: 400
        Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: 401
    patch_formats:
        json: ['application/merge-patch+json']
    graphql:
        enabled: false
    swagger:
        versions: [3]
    enable_swagger_ui: true
